name: raxxla
description: Universal Cartographics stellar cartography database.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fixnum: ^0.10.11
  cupertino_icons: ^1.0.1
  google_fonts: ^1.1.1
  grpc: ^2.9.0
  protobuf: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
