EDSM = {
    'planet': {
        'id': 'id64',
        'system_id': 'systemId64',
        'relative_id': 'bodyId',
        'name': 'name',
        'atmosphere.type': 'atmosphereType',
        'metadata.type': 'subType',
        'metadata.distance': 'distanceToArrival',
        'metadata.mass': 'earthMasses',
        'metadata.gravity': 'gravity',
        'metadata.landable': 'isLandable',
        'metadata.radius': 'radius',
        'metadata.temperature': 'surfaceTemperature',
        'metadata.pressure': 'surfacePressure',
        'metadata.volcanism': 'volcanismType',
        'metadata.terraforming': 'terraformingState',
        'orbit.period': 'orbitalPeriod',
        'orbit.rotational_period': 'rotationalPeriod',
        'orbit.tidally_locked': 'rotationalPeriodTidallyLocked',
        'orbit.periapsis': 'argOfPeriapsis',
        'orbit.eccentricity': 'orbitalEccentricity',
        'orbit.inclination': 'orbitalInclination',
        'orbit.semimajor_axis': 'semiMajorAxis',
        'orbit.axial_tilt': 'axialTilt',
        'repeated_fields': {
            'atmosphere.composition': {
                'key': 'atmosphereComposition',
                'type': 'composition',
            },
            'belts': {
                'key': 'belts',
                'type': 'ringlike',
            },
            'composition': {
                'key': 'solidComposition',
                'type': 'composition',
            },
            'materials': {
                'key': 'materials',
                'type': 'composition',
            },
            'parents': {
                'key': 'parents',
                'type': 'parents',
            },
            'rings': {
                'key': 'rings',
                'type': 'ringlike',
            },
        },
        'timestamp_fields': {
            'updated': 'updateTime',
        },
    },
    'population': {
        'base': {
            'system_id': 'id64',
            'allegiance': 'allegiance',
            'government': 'government',
            'state': 'state',
            'economy': 'economy',
            'security': 'security',
            'population': 'population',
            'timestamp_fields': {
                'updated': 'date',
            },
        },
        'faction': {
            'id': 'id',
            'name': 'name',
            'allegiance': 'allegiance',
            'government': 'government',
            'influence': 'influence',
            'happiness': 'happiness',
            'player_faction': 'isPlayer',
        },
        'state': {
            'active': 'activeStates',
            'pending': 'pendingStates',
            'recovering': 'recoveringStates',
        },
    },
    'powerplay': {
        'system_id': 'id64',
        'power.name': 'power',
        'power.state': 'powerState',
        'allegiance': 'allegiance',
        'government': 'government',
        'state': 'state',
        'timestamp_fields': {
            'updated': 'date',
        },
    },
    'star': {
        'id': 'id64',
        'system_id': 'systemId64',
        'relative_id': 'bodyId',
        'name': 'name',
        'metadata.type': 'subType',
        'metadata.distance': 'distanceToArrival',
        'metadata.reserve_level': 'reserveLevel',
        'metadata.spectral_class': 'spectralClass',
        'metadata.solar_masses': 'solarMasses',
        'metadata.solar_radius': 'solarRadius',
        'metadata.luminosity': 'luminosity',
        'metadata.temperature': 'surfaceTemperature',
        'orbit.period': 'orbitalPeriod',
        'orbit.rotational_period': 'rotationalPeriod',
        'orbit.tidally_locked': 'rotationalPeriodTidallyLocked',
        'orbit.periapsis': 'argOfPeriapsis',
        'orbit.eccentricity': 'orbitalEccentricity',
        'orbit.inclination': 'orbitalInclination',
        'orbit.semimajor_axis': 'semiMajorAxis',
        'orbit.axial_tilt': 'axialTilt',
        'repeated_fields': {
            'belts': {
                'key': 'belts',
                'type': 'ringlike',
            },
            'parents': {
                'key': 'parents',
                'type': 'parents',
            },
            'rings': {
                'key': 'rings',
                'type': 'ringlike',
            },
        },
        'timestamp_fields': {
            'updated': 'updateTime',
        },
    },
    'station': {
        'id': 'id',
        'system_id': 'systemId64',
        'name': 'name',
        'metadata.type': 'type',
        'metadata.distance': 'distanceToArrival',
        'metadata.allegiance': 'allegiance',
        'metadata.controlling_faction': 'controllingFaction.id',
        'metadata.government': 'government',
        'economy.id': 'marketId',
        'economy.type': 'economy',
        'economy.sub_type': 'secondEconomy',
        'services.market': 'haveMarket',
        'services.shipyard': 'haveShipyard',
        'services.outfitting': 'haveOutfitting',
        'timestamp_fields': {
            'updated': 'updateTime.information',
        },
    },
    'system': {
        'id': 'id64',
        'name': 'name',
        'coordinates.x': 'coords.x',
        'coordinates.y': 'coords.y',
        'coordinates.z': 'coords.z',
        'timestamp_fields': {
            'timestamp': 'date',
        },
    },
}