type: google.api.Service
name: raxxla.endpoints.raxxla.cloud.goog

title: Raxxla gRPC API
apis:
- name: raxxla.Raxxla

usage:
  rules:
  - selector: raxxla.Raxxla.ConvertPowerplayJson
    allow_unregistered_calls: true