load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

py_proto_library(
  name = "bodies_py_proto",
  srcs = ["bodies.proto"],
  deps = ["@com_google_protobuf//:protobuf_python"],
  visibility = ["//visibility:public"],
)

py_proto_library(
  name = "settlement_py_proto",
  srcs = ["settlement.proto"],
  deps = ["@com_google_protobuf//:protobuf_python"],
  visibility = ["//visibility:public"],
)

py_proto_library(
  name = "society_py_proto",
  srcs = ["society.proto"],
  deps = ["@com_google_protobuf//:protobuf_python"],
  visibility = ["//visibility:public"],
)

py_proto_library(
  name = "system_py_proto",
  srcs = ["system.proto"],
  deps = ["@com_google_protobuf//:protobuf_python"],
  visibility = ["//visibility:public"],
)
