load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

py_proto_library(
    name = "raxxla_proto",
    srcs = [
        "bodies.proto",
        "settlement.proto",
        "society.proto",
        "system.proto",
    ],
    visibility = ["//visibility:public"],
)
