name: Build and deploy to GCR
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build
        run: |-
            gcloud builds submit \
              --quiet \
              --tag "gcr.io/${{ secrets.RUN_PROJECT }}/raxxla:$GITHUB_SHA"
