name: Build and deploy to AWS ECR
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Build application image
        run: docker build -t raxxla:latest .
      - name: Push image to ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 209604952396.dkr.ecr.us-west-2.amazonaws.com
          docker tag raxxla:latest 209604952396.dkr.ecr.us-west-2.amazonaws.com/raxxla:latest
          docker push 209604952396.dkr.ecr.us-west-2.amazonaws.com/raxxla:latest
